<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2023-05-22T19:35:53+09:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      recaptcha_v3.send_ip
 * @group     captcha
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'recaptcha_v3' => [
        'site_key' => '6LfwxywmAAAAAHwzxQ8s2sn_ekKdVyeccAwzKufa',
        'secret_key' => '6LfwxywmAAAAAFgbgJzZYoVtMZ6VeWo-xgeZvuDH',
        'score' => 0.5,
        'position' => 'bottomright',
        'log_score' => true,
        'send_ip' => false,
    ],
];
