<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2022-06-05T19:54:22+09:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'オスカーのポートフォリオサイト',
            'seo' => [
                'canonical_url' => 'https://concrete.oscarchair.jp/',
                'canonical_url_alternative' => '',
                'canonical_tag' => [
                    'enabled' => true,
                ],
            ],
        ],
    ],
];